In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
# houses my function to connect to Codeup DB
import wrangle
pd.set_option('display.max_columns', None)

In [5]:
df = wrangle.get_zillow_data()

In [91]:
df = pd.read_csv('zillow_data.csv')

/var/folders/9q/9mllqnsn2vq07btq58zw9zzc0000gn/T/ipykernel_20053/3830838990.py:1: DtypeWarning: Columns (66) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('zillow_data.csv')

In [92]:
# df.info()

In [93]:
print(df.shape)
df = df.sort_values(by = 'transactiondate')
df = df.drop_duplicates(subset = 'parcelid', keep= 'last')
df = df.drop(columns = ['typeconstructiontypeid','storytypeid','heatingorsystemtypeid',
                  'buildingclasstypeid', 'architecturalstyletypeid','airconditioningtypeid',
                  'airconditioningtypeid','Unnamed: 0'])
# df[['transactiondate','parcelid']][df.duplicated(subset = 'parcelid') == True].sort_values(by = 'parcelid')
print(df.shape)

(77613, 70)
(77414, 63)

In [94]:
df

,parcelid,propertylandusetypeid,id,basementsqft,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedbathnbr,decktypeid,finishedfloor1squarefeet,calculatedfinishedsquarefeet,finishedsquarefeet12,finishedsquarefeet13,finishedsquarefeet15,finishedsquarefeet50,finishedsquarefeet6,fips,fireplacecnt,fullbathcnt,garagecarcnt,garagetotalsqft,hashottuborspa,latitude,longitude,lotsizesquarefeet,poolcnt,poolsizesum,pooltypeid10,pooltypeid2,pooltypeid7,propertycountylandusecode,propertyzoningdesc,rawcensustractandblock,regionidcity,regionidcounty,regionidneighborhood,regionidzip,roomcnt,threequarterbathnbr,unitcnt,yardbuildingsqft17,yardbuildingsqft26,yearbuilt,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyflag,taxdelinquencyyear,censustractandblock,propertylandusedesc,id.1,logerror,transactiondate,airconditioningdesc,architecturalstyledesc,buildingclassdesc,heatingorsystemdesc,storydesc,typeconstructiondesc
0,14297519,261.0,1727539,NaN,3.5,4.0,NaN,3.5,NaN,NaN,3100.0,3100.0,NaN,NaN,NaN,NaN,6059.0,NaN,3.0,2.0,633.0,NaN,33634931.0,-117869207.0,4506.0,NaN,NaN,NaN,NaN,NaN,122,NaN,6.059063e+07,53571.0,1286.0,NaN,96978.0,0.0,1.0,NaN,NaN,NaN,1998.0,NaN,NaN,485713.0,1023282.0,2016.0,537569.0,11013.72,NaN,NaN,6.059063e+13,Single Family Residential,0,0.025595,2017-01-01,NaN,NaN,NaN,NaN,NaN,NaN
1,17052889,261.0,1387261,NaN,1.0,2.0,NaN,1.0,NaN,1465.0,1465.0,1465.0,NaN,NaN,1465.0,NaN,6111.0,1.0,1.0,1.0,0.0,NaN,34449266.0,-119281531.0,12647.0,NaN,NaN,NaN,NaN,NaN,1110,NaN,6.111001e+07,13091.0,2061.0,NaN,97099.0,5.0,NaN,NaN,NaN,NaN,1967.0,1.0,NaN,88000.0,464000.0,2016.0,376000.0,5672.48,NaN,NaN,6.111001e+13,Single Family Residential,1,0.055619,2017-01-01,NaN,NaN,NaN,NaN,NaN,NaN
2,14186244,261.0,11677,NaN,2.0,3.0,NaN,2.0,NaN,NaN,1243.0,1243.0,NaN,NaN,NaN,NaN,6059.0,NaN,2.0,2.0,440.0,NaN,33886168.0,-117823170.0,8432.0,1.0,NaN,NaN,NaN,1.0,122,NaN,6.059022e+07,21412.0,1286.0,NaN,97078.0,6.0,NaN,NaN,NaN,NaN,1962.0,1.0,NaN,85289.0,564778.0,2016.0,479489.0,6488.30,NaN,NaN,6.059022e+13,Single Family Residential,2,0.005383,2017-01-01,NaN,NaN,NaN,NaN,NaN,NaN
3,12177905,261.0,2288172,NaN,3.0,4.0,8.0,3.0,NaN,NaN,2376.0,2376.0,NaN,NaN,NaN,NaN,6037.0,NaN,3.0,NaN,NaN,NaN,34245180.0,-118240722.0,13038.0,1.0,NaN,NaN,NaN,1.0,0101,LCR110000*,6.037300e+07,396551.0,3101.0,NaN,96330.0,0.0,NaN,1.0,NaN,NaN,1970.0,NaN,NaN,108918.0,145143.0,2016.0,36225.0,1777.51,NaN,NaN,6.037300e+13,Single Family Residential,3,-0.103410,2017-01-01,NaN,NaN,NaN,Central,NaN,NaN
4,10887214,266.0,1970746,NaN,3.0,3.0,8.0,3.0,NaN,NaN,1312.0,1312.0,NaN,NaN,NaN,NaN,6037.0,NaN,3.0,NaN,NaN,NaN,34185120.0,-118414640.0,278581.0,1.0,NaN,NaN,NaN,1.0,010C,LAR3,6.037124e+07,12447.0,3101.0,268548.0,96451.0,0.0,NaN,1.0,NaN,NaN,1964.0,NaN,NaN,73681.0,119407.0,2016.0,45726.0,1533.89,NaN,NaN,6.037124e+13,Condominium,4,0.006940,2017-01-01,Central,NaN,NaN,Central,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77608,10833991,266.0,2864704,NaN,3.0,3.0,8.0,3.0,NaN,NaN,1741.0,1741.0,NaN,NaN,NaN,NaN,6037.0,NaN,3.0,NaN,NaN,NaN,34202400.0,-118502000.0,59487.0,1.0,NaN,NaN,NaN,1.0,010C,LARD3,6.037132e+07,12447.0,3101.0,32368.0,96415.0,0.0,NaN,1.0,NaN,NaN,1980.0,NaN,NaN,265000.0,379000.0,2016.0,114000.0,4685.34,NaN,NaN,6.037132e+13,Condominium,77608,-0.002245,2017-09-20,Central,NaN,NaN,Central,NaN,NaN
77609,11000655,261.0,673515,NaN,2.0,2.0,6.0,2.0,NaN,NaN,1286.0,1286.0,NaN,NaN,NaN,NaN,6037.0,NaN,2.0,NaN,NaN,NaN,34245368.0,-118282383.0,47405.0,NaN,NaN,NaN,NaN,NaN,0100,LARE40,6.037101e+07,12447.0,3101.0,27328.0,96284.0,0.0,NaN,1.0,NaN,NaN,1940.0,NaN,NaN,70917.0,354621.0,2016.0,283704.0,4478.43,NaN,NaN,6.037101e+13,Single Family Residential,77609,0.020615,2017-09-20,NaN,NaN,NaN,Central,NaN,NaN
77611,12773139,261.0,1843709,NaN,1.0,3.0,4.0,1.0,NaN,NaN,1032.0,1032.0,NaN,NaN,NaN,NaN,6037.0,NaN,1.0,NaN,NaN,NaN,34040895.0,-118038169.0,5074.0,NaN,NaN,NaN,NaN,NaN,0100,SER1*,6.037434e+07,36502.0,3101.0,NaN,96480.0,0.0,NaN,1.0,NaN,NaN,1954.0,NaN,NaN,32797.0,49546.0,2016.0,16749.0,876.43,NaN,NaN,6.037434e+13,Single Family Residential,77611,0.037129,2017-09-21,Central,NaN,NaN,Central,NaN,NaN
77610,17239384,261.0,2968375,NaN,2.0,4.0,NaN,2.0,NaN,1612.0,1612.0,1612.0,NaN,NaN,1612.0,NaN,6111.0,1.0,2.0,2.0,560.0,NaN,34300140.0,-118706327.0,12105.0,NaN,NaN,NaN,NaN,NaN,1111,NaN,6.111008e+07,27110.0,2061.0,NaN,97116.0,7.0,NaN,NaN,656.0,NaN,1964.0,1.0,NaN,50683.0,67205.0,2016.0,16522.0,1107.48,NaN,NaN,6.111008e+13,Single Family Residential,77610,0.013209,2017-09-21,NaN,NaN,NaN,NaN,NaN,NaN
77612,12826780,261.0,1187175,NaN,2.0,3.0,6.0,2.0,NaN,NaN,1762.0,1762.0,NaN,NaN,NaN,NaN,6037.0,NaN,2.0,NaN,NaN,NaN,33937685.0,-117996709.0,6347.0,NaN,NaN,NaN,NaN,NaN,0100,WHR16000*,6.037503e+07,14634.0,3101.0,NaN,96171.0,0.0,NaN,1.0,NaN,NaN,1955.0,NaN,NaN,140000.0,522000.0,2016.0,382000.0,6317.15,NaN,NaN,6.037503e+13,Single Family Residential,77612,0.007204,2017-09-25,NaN,NaN,NaN,Central,NaN,NaN

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 77414 entries, 0 to 77612
Data columns (total 63 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   parcelid                      77414 non-null  int64
 1   propertylandusetypeid         77381 non-null  float64
 2   id                            77414 non-null  int64
 3   basementsqft                  50 non-null     float64
 4   bathroomcnt                   77381 non-null  float64
 5   bedroomcnt                    77381 non-null  float64
 6   buildingqualitytypeid         49672 non-null  float64
 7   calculatedbathnbr             76772 non-null  float64
 8   decktypeid                    614 non-null    float64
 9   finishedfloor1squarefeet      6023 non-null   float64
 10  calculatedfinishedsquarefeet  77185 non-null  float64
 11  finishedsquarefeet12          73749 non-null  float64
 12  finishedsquarefeet13          41 non-null     float64
 13  finishedsquarefeet15          3009 non-null   float64
 14  finishedsquarefeet50          6023 non-null   float64
 15  finishedsquarefeet6           386 non-null    float64
 16  fips                          77381 non-null  float64
 17  fireplacecnt                  8276 non-null   float64
 18  fullbathcnt                   76772 non-null  float64
 19  garagecarcnt                  25474 non-null  float64
 20  garagetotalsqft               25474 non-null  float64
 21  hashottuborspa                1538 non-null   float64
 22  latitude                      77381 non-null  float64
 23  longitude                     77381 non-null  float64
 24  lotsizesquarefeet             69142 non-null  float64
 25  poolcnt                       16137 non-null  float64
 26  poolsizesum                   867 non-null    float64
 27  pooltypeid10                  464 non-null    float64
 28  pooltypeid2                   1074 non-null   float64
 29  pooltypeid7                   15042 non-null  float64
 30  propertycountylandusecode     77381 non-null  object
 31  propertyzoningdesc            50331 non-null  object
 32  rawcensustractandblock        77381 non-null  float64
 33  regionidcity                  75910 non-null  float64
 34  regionidcounty                77381 non-null  float64
 35  regionidneighborhood          30890 non-null  float64
 36  regionidzip                   77331 non-null  float64
 37  roomcnt                       77381 non-null  float64
 38  threequarterbathnbr           10096 non-null  float64
 39  unitcnt                       50563 non-null  float64
 40  yardbuildingsqft17            2388 non-null   float64
 41  yardbuildingsqft26            70 non-null     float64
 42  yearbuilt                     77118 non-null  float64
 43  numberofstories               17560 non-null  float64
 44  fireplaceflag                 172 non-null    float64
 45  structuretaxvaluedollarcnt    77269 non-null  float64
 46  taxvaluedollarcnt             77380 non-null  float64
 47  assessmentyear                77381 non-null  float64
 48  landtaxvaluedollarcnt         77379 non-null  float64
 49  taxamount                     77376 non-null  float64
 50  taxdelinquencyflag            2886 non-null   object
 51  taxdelinquencyyear            2886 non-null   float64
 52  censustractandblock           77137 non-null  float64
 53  propertylandusedesc           77381 non-null  object
 54  id.1                          77414 non-null  int64
 55  logerror                      77414 non-null  float64
 56  transactiondate               77414 non-null  object
 57  airconditioningdesc           24953 non-null  object
 58  architecturalstyledesc        206 non-null    object
 59  buildingclassdesc             15 non-null     object
 60  heatingorsystemdesc           49440 non-null  object
 61  storydesc                     50 non-null     object
 62  typeconstructiondesc          222 non-null    object
dtypes: float64(49), int64(3), object(11)
memory usage: 37.8+ MB

In [46]:
df.dtypes

parcelid                    int64
propertylandusetypeid     float64
id                          int64
basementsqft              float64
bathroomcnt               float64
                           ...
architecturalstyledesc     object
buildingclassdesc          object
heatingorsystemdesc        object
storydesc                  object
typeconstructiondesc       object
Length: 63, dtype: object

In [49]:
df.shape

(77414, 63)

In [50]:
df.value_counts()

Series([], dtype: int64)

In [51]:
df.describe()

,parcelid,propertylandusetypeid,id,basementsqft,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedbathnbr,decktypeid,finishedfloor1squarefeet,calculatedfinishedsquarefeet,finishedsquarefeet12,finishedsquarefeet13,finishedsquarefeet15,finishedsquarefeet50,finishedsquarefeet6,fips,fireplacecnt,fullbathcnt,garagecarcnt,garagetotalsqft,hashottuborspa,latitude,longitude,lotsizesquarefeet,poolcnt,poolsizesum,pooltypeid10,pooltypeid2,pooltypeid7,rawcensustractandblock,regionidcity,regionidcounty,regionidneighborhood,regionidzip,roomcnt,threequarterbathnbr,unitcnt,yardbuildingsqft17,yardbuildingsqft26,yearbuilt,numberofstories,fireplaceflag,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,taxdelinquencyyear,censustractandblock,id.1,logerror
count,7.741400e+04,77381.000000,7.741400e+04,50.000000,77381.000000,77381.000000,49672.000000,76772.000000,614.0,6023.000000,77185.000000,73749.000000,41.000000,3009.000000,6023.000000,386.000000,77381.000000,8276.000000,76772.000000,25474.000000,25474.000000,1538.0,7.738100e+04,7.738100e+04,6.914200e+04,16137.0,867.000000,464.0,1074.0,15042.0,7.738100e+04,75910.000000,77381.000000,30890.000000,77331.000000,77381.000000,10096.000000,50563.000000,2388.000000,70.000000,77118.000000,17560.000000,172.0,7.726900e+04,7.738000e+04,77381.0,7.737900e+04,77376.000000,2886.000000,7.713700e+04,77414.000000,77414.000000
mean,1.300670e+07,261.826340,1.495774e+06,679.720000,2.299130,3.053489,6.534587,2.316867,66.0,1366.512535,1785.219939,1760.522543,1389.853659,2357.791625,1381.771542,2082.500000,6048.819232,1.191155,2.250482,1.815459,350.111957,1.0,3.400837e+07,-1.182036e+08,2.996928e+04,1.0,517.916955,1.0,1.0,1.0,6.049129e+07,33671.242708,2534.158333,187734.864066,96587.086822,1.476952,1.009608,1.110021,305.411223,216.385714,1968.635831,1.434738,1.0,1.893145e+05,4.901345e+05,2016.0,3.010954e+05,5995.532346,14.087318,6.049673e+13,38847.638334,0.016578
std,3.480690e+06,5.141199,8.612720e+05,689.703546,0.996651,1.139096,1.721953,0.979755,0.0,671.308125,954.049286,934.024340,123.531688,1188.775210,726.468878,1240.382784,20.748199,0.491080,0.966552,0.588345,261.681641,0.0,2.653888e+05,3.594826e+05,1.233711e+05,0.0,156.716017,0.0,0.0,0.0,2.059052e+05,47169.815982,801.593352,165118.791740,3798.347098,2.824386,0.118630,1.171154,238.392793,190.177514,23.786032,0.544569,0.0,2.300874e+05,6.534440e+05,0.0,4.925960e+05,7622.844153,2.185663,1.535242e+12,22403.927709,0.170342
min,1.071186e+07,31.000000,3.490000e+02,38.000000,0.000000,0.000000,1.000000,1.000000,66.0,44.000000,128.000000,128.000000,1056.000000,598.000000,44.000000,380.000000,6037.000000,1.000000,1.000000,0.000000,0.000000,1.0,3.333953e+07,-1.194754e+08,2.360000e+02,1.0,24.000000,1.0,1.0,1.0,6.037101e+07,3491.000000,1286.000000,6952.000000,95982.000000,0.000000,1.000000,1.000000,11.000000,12.000000,1824.000000,1.000000,1.0,4.400000e+01,1.000000e+03,2016.0,1.610000e+02,19.920000,3.000000,6.037101e+13,0.000000,-4.655420
25%,1.153834e+07,261.000000,7.524398e+05,273.000000,2.000000,2.000000,6.000000,2.000000,66.0,955.000000,1182.000000,1172.000000,1344.000000,1625.000000,956.000000,993.750000,6037.000000,1.000000,2.000000,2.000000,0.000000,1.0,3.381457e+07,-1.184153e+08,5.700000e+03,1.0,424.000000,1.0,1.0,1.0,6.037311e+07,12447.000000,1286.000000,46736.000000,96193.000000,0.000000,1.000000,1.000000,170.000000,61.500000,1953.000000,1.000000,1.0,8.426500e+04,2.070000e+05,2016.0,8.550400e+04,2715.632500,14.000000,6.037311e+13,19458.250000,-0.024387
50%,1.253072e+07,261.000000,1.498474e+06,515.000000,2.000000,3.000000,6.000000,2.000000,66.0,1257.000000,1543.000000,1523.000000,1440.000000,2094.000000,1259.000000,1812.500000,6037.000000,1.000000,2.000000,2.000000,436.000000,1.0,3.402200e+07,-1.181808e+08,7.206000e+03,1.0,500.000000,1.0,1.0,1.0,6.037603e+07,25218.000000,3101.000000,118849.000000,96389.000000,0.000000,1.000000,1.000000,251.000000,164.500000,1970.000000,1.000000,1.0,1.364990e+05,3.589755e+05,2016.0,2.033720e+05,4450.695000,15.000000,6.037603e+13,38870.500000,0.006624
75%,1.421149e+07,266.000000,2.241722e+06,796.500000,3.000000,4.000000,8.000000,3.000000,66.0,1615.000000,2113.000000,2076.000000,1440.000000,2838.000000,1621.500000,3053.500000,6059.000000,1.000000,3.000000,2.000000,493.000000,1.0,3.417439e+07,-1.179284e+08,1.183100e+04,1.0,600.000000,1.0,1.0,1.0,6.059042e+07,45457.000000,3101.000000,274765.000000,96987.000000,0.000000,1.000000,1.000000,364.000000,310.500000,1987.000000,2.000000,1.0,2.187870e+05,5.690015e+05,2016.0,3.667965e+05,6927.790000,15.000000,6.059042e+13,58253.750000,0.039211
max,1.676893e+08,275.000000,2.985182e+06,3560.000000,18.000000,16.000000,12.000000,18.000000,66.0,6912.000000,35640.000000,21929.000000,1560.000000,35640.000000,12467.000000,5598.000000,6111.000000,5.000000,18.000000,14.000000,4251.000000,1.0,3.481877e+07,-1.175546e+08,6.971010e+06,1.0,1500.000000,1.0,1.0,1.0,6.111009e+07,396556.000000,3101.000000,764167.000000,399675.000000,15.000000,7.000000,237.000000,3191.000000,868.000000,2016.000000,6.000000,1.0,1.142179e+07,4.906124e+07,2016.0,4.895220e+07,586639.300000,99.000000,4.830301e+14,77612.000000,5.262999

In [52]:
def nulls_by_col(df):
    """
    This function will:
        - take in a dataframe
        - assign a variable to a Series of total row nulls for ea/column
        - assign a variable to find the percent of rows w/nulls
        - output a df of the two variables.
    """
    num_missing = df.isnull().sum()
    pct_miss = (num_missing / df.shape[0]) * 100
    cols_missing = pd.DataFrame({
                    'num_rows_missing': num_missing,
                    'percent_rows_missing': pct_miss
                    })
    
    return  cols_missing

In [53]:
into_on_dataframe = nulls_by_col(df)

In [54]:
into_on_dataframe

                        num_rows_missing  percent_rows_missing
parcelid                               0              0.000000
propertylandusetypeid                 33              0.042628
id                                     0              0.000000
basementsqft                       77364             99.935412
bathroomcnt                           33              0.042628
...                                  ...                   ...
architecturalstyledesc             77208             99.733898
buildingclassdesc                  77399             99.980624
heatingorsystemdesc                27974             36.135583
storydesc                          77364             99.935412
typeconstructiondesc               77192             99.713230

[63 rows x 2 columns]

In [63]:
def handle_missing_values(df, prop_required_columns=0.5, prop_required_rows=0.75):
    """
    This function will:
    - take in: 
        - a dataframe
        - column threshold (defaulted to 0.5)
        - row threshold (defaulted to 0.75)
    - calculates the minimum number of non-missing values required for each column/row to be retained
    - drops columns/rows with a high proportion of missing values.
    - returns the new df
    """
    
    column_threshold = int(round(prop_required_columns * len(df.index), 0))
    df = df.dropna(axis=1, thresh=column_threshold)
    
    row_threshold = int(round(prop_required_rows * len(df.columns), 0))
    df = df.dropna(axis=0, thresh=row_threshold)
    
    return df

In [65]:
missing_values_df = handle_missing_values(df, prop_required_columns=0.5, prop_required_rows=0.75)

In [66]:
missing_values_df

,parcelid,propertylandusetypeid,id,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedbathnbr,calculatedfinishedsquarefeet,finishedsquarefeet12,fips,fullbathcnt,latitude,longitude,lotsizesquarefeet,propertycountylandusecode,propertyzoningdesc,rawcensustractandblock,regionidcity,regionidcounty,regionidzip,roomcnt,unitcnt,yearbuilt,structuretaxvaluedollarcnt,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,censustractandblock,propertylandusedesc,id.1,logerror,transactiondate,heatingorsystemdesc
0,14297519,261.0,1727539,3.5,4.0,NaN,3.5,3100.0,3100.0,6059.0,3.0,33634931.0,-117869207.0,4506.0,122,NaN,6.059063e+07,53571.0,1286.0,96978.0,0.0,NaN,1998.0,485713.0,1023282.0,2016.0,537569.0,11013.72,6.059063e+13,Single Family Residential,0,0.025595,2017-01-01,NaN
1,17052889,261.0,1387261,1.0,2.0,NaN,1.0,1465.0,1465.0,6111.0,1.0,34449266.0,-119281531.0,12647.0,1110,NaN,6.111001e+07,13091.0,2061.0,97099.0,5.0,NaN,1967.0,88000.0,464000.0,2016.0,376000.0,5672.48,6.111001e+13,Single Family Residential,1,0.055619,2017-01-01,NaN
2,14186244,261.0,11677,2.0,3.0,NaN,2.0,1243.0,1243.0,6059.0,2.0,33886168.0,-117823170.0,8432.0,122,NaN,6.059022e+07,21412.0,1286.0,97078.0,6.0,NaN,1962.0,85289.0,564778.0,2016.0,479489.0,6488.30,6.059022e+13,Single Family Residential,2,0.005383,2017-01-01,NaN
3,12177905,261.0,2288172,3.0,4.0,8.0,3.0,2376.0,2376.0,6037.0,3.0,34245180.0,-118240722.0,13038.0,0101,LCR110000*,6.037300e+07,396551.0,3101.0,96330.0,0.0,1.0,1970.0,108918.0,145143.0,2016.0,36225.0,1777.51,6.037300e+13,Single Family Residential,3,-0.103410,2017-01-01,Central
4,10887214,266.0,1970746,3.0,3.0,8.0,3.0,1312.0,1312.0,6037.0,3.0,34185120.0,-118414640.0,278581.0,010C,LAR3,6.037124e+07,12447.0,3101.0,96451.0,0.0,1.0,1964.0,73681.0,119407.0,2016.0,45726.0,1533.89,6.037124e+13,Condominium,4,0.006940,2017-01-01,Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77608,10833991,266.0,2864704,3.0,3.0,8.0,3.0,1741.0,1741.0,6037.0,3.0,34202400.0,-118502000.0,59487.0,010C,LARD3,6.037132e+07,12447.0,3101.0,96415.0,0.0,1.0,1980.0,265000.0,379000.0,2016.0,114000.0,4685.34,6.037132e+13,Condominium,77608,-0.002245,2017-09-20,Central
77609,11000655,261.0,673515,2.0,2.0,6.0,2.0,1286.0,1286.0,6037.0,2.0,34245368.0,-118282383.0,47405.0,0100,LARE40,6.037101e+07,12447.0,3101.0,96284.0,0.0,1.0,1940.0,70917.0,354621.0,2016.0,283704.0,4478.43,6.037101e+13,Single Family Residential,77609,0.020615,2017-09-20,Central
77610,17239384,261.0,2968375,2.0,4.0,NaN,2.0,1612.0,1612.0,6111.0,2.0,34300140.0,-118706327.0,12105.0,1111,NaN,6.111008e+07,27110.0,2061.0,97116.0,7.0,NaN,1964.0,50683.0,67205.0,2016.0,16522.0,1107.48,6.111008e+13,Single Family Residential,77610,0.013209,2017-09-21,NaN
77611,12773139,261.0,1843709,1.0,3.0,4.0,1.0,1032.0,1032.0,6037.0,1.0,34040895.0,-118038169.0,5074.0,0100,SER1*,6.037434e+07,36502.0,3101.0,96480.0,0.0,1.0,1954.0,32797.0,49546.0,2016.0,16749.0,876.43,6.037434e+13,Single Family Residential,77611,0.037129,2017-09-21,Central
77612,12826780,261.0,1187175,2.0,3.0,6.0,2.0,1762.0,1762.0,6037.0,2.0,33937685.0,-117996709.0,6347.0,0100,WHR16000*,6.037503e+07,14634.0,3101.0,96171.0,0.0,1.0,1955.0,140000.0,522000.0,2016.0,382000.0,6317.15,6.037503e+13,Single Family Residential,77612,0.007204,2017-09-25,Central

In [103]:
df = df[(df.propertylandusedesc == 'Single Family Residential') | (df.propertylandusedesc == 'Mobile Home')]
# df = df[df.propertylandusedesc == 'Mobile Home']

df.propertylandusedesc.value_counts()

Single Family Residential    52320
Mobile Home                     74
Name: propertylandusedesc, dtype: int64

In [104]:
def get_upper_outliers(s, m=1.5):
    '''
    Given a series and a cutoff value, k, returns the upper outliers for the
    series.

    The values returned will be either 0 (if the point is not an outlier), or a
    number that indicates how far away from the upper bound the observation is.
    '''
    q1, q3 = s.quantile([.25, 0.75])
    iqr = q3 - q1
    upper_bound = q3 + (m * iqr)
    
    return s.apply(lambda x: max([x - upper_bound, 0]))

In [ ]:
def add_upper_outlier_columns(df, m=1.5):
    '''
    Add a column with the suffix _outliers for all the numeric columns
    in the given dataframe.
    '''
    for col in df.select_dtypes('number'):
        df[col + '_outliers_upper'] = get_upper_outliers(df[col], m)
    return df